version: "3"
services:
  nlpapi:
    container_name: nlpdev
    volumes:
      - ./lib:/app/lib
      - ./middleware:/app/middleware
      - ./routes:/app/routes
      - ./setup:/app/setup
      - ./state.js:/app/state.js
    env_file:
      - nlp_local_mongo.env
    build:
      context: .
      dockerfile: dev.Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - 3000:3000
    # OPTIONAL: run unauthenticated api
    # command: ['npm', 'run', 'start-dev-unauthed']
    command: ['npm', 'run', 'start-dev']
