version: '3'
services:
  nlpapi:
    container_name: nlpdev
    volumes:
      - ./state.js:/app/state.js
      - ./lib:/app/lib
      - ./routes:/app/routes
      - ./setup:/app/setup
    env_file:
      - nlp-atlas.env
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000